### ISSUE TITLE
Can I set parameters to search the data for a specific time period?

### ISSUE THREAD

**Issue by ghost** [terrill/YTCA#1]
For example, if I want to look at a YouTube channel that's been around since 2008, can I just set the parameters to gauge their performance for the past 12 months? Or month? etc etc?

**Comment by terrill** [comment]
This is a good idea. Certainly results could be filtered post-retrieval but hopefully this filtering can be implemented within the query to the YouTube API. That will result in fewer videos in the results, which means YTCA will be able to process them a lot faster since every video results in another query. I'll investigate.

**Comment by terrill** [comment]
Sorry this took so long. Date filtering has finally been added as of b3eed093682ba1386b2e6290f1a1ea2ca8fae68f
